apiVersion: v1
kind: Service
metadata:
  name : nodeport-service
spec:
  selector:
     app : node
  ports:
  - protocol : TCP
    port : 80
    targetPort : 8080
    nodePort : 32001
  type: NodePort

